---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Data
- type: document
  path: src/_data/hero.json
  label: hero
  match: "**/*"
- type: heading
  label: SideBar heading
- type: document
  path: src/index.html
  label: Home
- type: heading
  label: Layouts
- type: directory
  path: src/_includes/layouts
  label: Layouts
  create: all
  match: "**/*"
upload_dir: src/assets/images
public_path: _site/assets/images
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: _site
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: eleventy --serve
